In [1]:
from transformers import AutoTokenizer, AutoModel
import torch


#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


# Sentences we want sentence embeddings for
sentences = ['This is an example sentence', 'Each sentence is converted', 'Each sentence is converted']


# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('hiiamsid/sentence_similarity_hindi')
model = AutoModel.from_pretrained('hiiamsid/sentence_similarity_hindi')

# Tokenize sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling. In this case, mean pooling.
sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

print("Sentence embeddings:")
print(sentence_embeddings)


C:\Users\Asus\anaconda3\envs\aaaa\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


Sentence embeddings:
tensor([[ 0.1158, -0.1213, -0.9723,  ..., -0.7502,  0.5903, -0.7668],
        [ 0.3733,  1.5856,  0.0510,  ...,  0.7305,  1.2980,  0.9126],
        [ 0.3733,  1.5856,  0.0510,  ...,  0.7305,  1.2980,  0.9126]])


In [2]:
sentence_embeddings[0]

tensor([ 1.1582e-01, -1.2129e-01, -9.7234e-01,  7.2859e-01, -2.0651e+00,
        -1.0154e+00,  9.6246e-01,  4.6372e-01,  3.1825e-01, -2.2121e+00,
         9.2264e-01, -2.3044e+00,  9.6696e-01,  5.5065e-01,  3.7627e-01,
         6.1332e-01, -3.0545e-01, -1.4459e+00, -1.7499e+00, -7.8996e-01,
         3.7510e-02,  1.0460e-01,  1.0201e+00,  8.6167e-03,  6.2815e-01,
         6.3234e-01, -3.9543e-01, -1.1401e-01,  1.5255e-01, -1.5164e-01,
         6.2283e-01,  4.4481e-01,  5.5774e-01,  3.4345e-01, -2.9671e+00,
        -2.3015e-01, -1.7329e+00, -1.8282e+00, -8.4382e-01,  2.4336e-01,
         7.4170e-02,  1.1960e+00,  5.6357e-01,  7.1234e-01,  1.5219e-01,
        -6.7581e-01, -1.2204e+00, -1.3934e+00,  8.1908e-01, -8.5302e-01,
         1.1518e+00, -3.2921e-02,  4.7180e-01, -1.4536e+00,  4.5414e-01,
        -4.2277e-01, -7.2271e-01,  2.6621e-01,  1.3347e+00,  6.2028e-01,
         6.5338e-01, -1.2556e+00, -4.3374e-01,  4.4398e-02, -7.2440e-01,
        -1.2290e+00, -4.4309e-01, -5.3764e-02, -2.5

In [8]:
import pandas as pd
df = pd.read_csv("data_embedding.csv")
df

Unnamed: 0                sentence1  \
0              0                   Te Amo   
1              1       500 Days of Summer   
2              2                   1 LIVE   
3              3              11 Internet   
4              4              1800Flowers   
...          ...                      ...   
5660        5660  엔제리너스커피Angelinus Coffee   
5661        5661                  오늘 뭐 먹지   
5662        5662     인천공항 incheon airport   
5663        5663      케이투 아웃도어 K2 OUTDOOR   
5664        5664          ～One Piece～海贼王～   

                                              sentence2  
0     Jeu de Paume is an excellent art gallery in Paris  
1     Jeu de Paume is an excellent art gallery in Paris  
2     Jeu de Paume is an excellent art gallery in Paris  
3     Jeu de Paume is an excellent art gallery in Paris  
4     Jeu de Paume is an excellent art gallery in Paris  
...                                                 ...  
5660  Jeu de Paume is an excellent art gallery in Paris  
5661  Jeu de Paume is an excellent art gallery in Paris  
5662  Jeu de Paume is an excellent art gallery in Paris  
5663  Jeu de Paume is an excellent art gallery in Paris  
5664  Jeu de Paume is an excellent art gallery in Paris  

[5665 rows x 3 columns]

In [38]:
sentence1 = df.sentence1.tolist()

In [44]:
sentence2 = [df.sentence2[0]]

In [68]:
encoded_sentence= tokenizer(sentence2 + sentence1, padding=True, truncation=True, return_tensors="pt")

In [69]:
encoded_sentence

{'input_ids': tensor([[   101, 168639,  14976,  ...,      0,      0,      0],
        [   101,  16930, 113458,  ...,      0,      0,      0],
        [   101,  15644,  45268,  ...,      0,      0,      0],
        ...,
        [   101, 254977, 318737,  ...,      0,      0,      0],
        [   101,  13300,  15704,  ...,      0,      0,      0],
        [   101,  14298, 324893,  ...,      0,      0,      0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [70]:
with torch.no_grad():
    model_output = model(**encoded_sentence)

In [72]:
sentence_embed = mean_pooling(model_output, encoded_sentence['attention_mask'])

In [75]:
print(sentence_embed)
type(sentence_embed)

tensor([[ 1.5237, -1.0498, -1.2545,  ..., -0.9405,  0.0829, -0.3809],
        [ 1.2747,  1.0040,  1.1275,  ..., -1.6415, -0.5089, -1.1023],
        [ 1.3412,  1.0317,  0.0563,  ..., -0.8517,  0.2686, -0.5459],
        ...,
        [ 0.6489,  0.0226,  0.3716,  ...,  1.9176, -0.2532, -0.1090],
        [ 1.9236, -0.4470,  2.2669,  ...,  0.0225, -1.0045,  0.1952],
        [ 0.6990,  0.1266,  1.4319,  ...,  0.3685, -0.3460, -0.6829]])


torch.Tensor

In [91]:
sentence_embed[0]

tensor([ 1.5237e+00, -1.0498e+00, -1.2545e+00,  1.5110e+00, -1.2459e+00,
         2.0503e-01, -7.5617e-01,  1.0983e-01,  8.5774e-01, -3.0137e-01,
         4.5281e-01,  2.9756e-01,  3.3330e-02,  3.4647e-01,  6.1259e-01,
        -3.1451e-01,  2.7062e-01, -9.1878e-01, -3.0921e-01,  7.0546e-01,
         7.9030e-01,  9.1692e-01,  5.0288e-01,  8.9223e-01,  1.3696e-01,
         2.1531e-01,  3.1703e-01,  9.7721e-01,  6.7263e-02, -6.4496e-02,
         1.0563e-01,  9.2573e-01,  4.3204e-01,  1.3358e+00, -3.6995e-01,
        -2.3905e-01,  1.1624e-01, -1.1477e+00,  3.7026e-02, -9.2407e-01,
         1.8063e+00, -1.2430e-01,  6.4875e-01, -2.8752e-01, -6.9613e-01,
         9.4075e-01, -1.0811e-01,  1.2948e+00, -2.3372e+00, -1.2990e+00,
        -2.1417e-01, -6.8413e-01,  7.5004e-02, -3.1543e-01,  4.3532e-01,
         9.6749e-01, -1.3768e+00, -1.4370e+00,  3.3527e-02,  3.5484e-01,
         9.7333e-01, -5.3400e-01, -1.8788e-01,  1.1473e+00, -4.2176e-02,
        -7.3097e-01, -6.0234e-01, -1.0428e+00, -3.6